"""first

Revision ID: 2eac467d2fb1
Revises: 
Create Date: 2022-09-10 20:59:50.737232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eac467d2fb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.Column('posts_text', sa.String(length=350), nullable=True),
    sa.Column('posts_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('posts_id')
    )
    op.create_table('Users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('users_name', sa.String(), nullable=True),
    sa.Column('users_email', sa.String(), nullable=True),
    sa.Column('users_password', sa.String(), nullable=True),
    sa.Column('users_date', sa.DateTime(), nullable=True),
    sa.Column('users_status', sa.Boolean(), nullable=True),
    sa.Column('users_is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('users_email'),
    sa.UniqueConstraint('users_name')
    )
    op.create_index(op.f('ix_Users_users_id'), 'Users', ['users_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_table('Posts')
    # ### end Alembic commands ###
